feat: upgrade to RN 0.73.6 (#1439)
Signed-off-by: Mostafa Gamal <moscd3@gmail.com>
Signed-off-by: Mohamed Abd El-Samie Ahmad Mansour <masmas04@gmail.com>
Signed-off-by: fc-santos <filipesantos@live.ca>
Signed-off-by: ClaudeArs <claudears2474@gmail.com>
Signed-off-by: Mostafa Gamal <46829557+MosCD3@users.noreply.github.com>
Signed-off-by: Bryce McMath <bryce.j.mcmath@gmail.com>
Co-authored-by: Mohamed Abd El-Samie Ahmad Mansour <masmas04@gmail.com>
Co-authored-by: Filipe Santos <48060475+fc-santos@users.noreply.github.com>
Co-authored-by: ClaudeArs <107423901+ClaudeArs@users.noreply.github.com>
Co-authored-by: Bryce McMath <32586431+bryce-mcmath@users.noreply.github.com>
Co-authored-by: Mohamed Mansour <95133592+MaSMas0@users.noreply.github.com>

diff --git a/packages/legacy/app/android/gradlew b/packages/legacy/app/android/gradlew
--- a/packages/legacy/app/android/gradlew
+++ b/packages/legacy/app/android/gradlew
@@ -37,14 +37,14 @@ while [ -h "$PRG" ] ; do
 done
 SAVED="`pwd`"
 cd "`dirname \"$PRG\"`/" >/dev/null
-APP_HOME="`pwd -P`"
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME="`pwd -P`" > /dev/null
 cd "$SAVED" >/dev/null
 
 APP_NAME="Gradle"
 APP_BASE_NAME=`basename "$0"`
 
-# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD="maximum"
@@ -98,12 +98,13 @@ location of your Java installation."
     fi
 else
     JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
-
 # Increase the maximum file descriptors if we can.
 if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
     MAX_FD_LIMIT=`ulimit -H -n`
@@ -177,6 +178,10 @@ save () {
 }
 APP_ARGS=`save "$@"`
 
+ 
+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+ 
 # Collect all arguments for the java command, following the shell quoting and substitution rules
 eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
 
